import { useEffect, useState } from 'react';
import { Box, Typography, Button, Paper, Table, TableBody, TableCell, TableContainer, TableHead, TableRow, Chip, Dialog, DialogTitle, DialogContent, TextField, DialogActions, FormControl, InputLabel, Select, MenuItem, Snackbar, Alert, CircularProgress, Pagination } from '@mui/material';
import AddIcon from '@mui/icons-material/Add';
import client from '../api/client';

const limit = 10;

const totalPagesCalculator = (totalTasks: number, limit: number): number => {
    if (totalTasks === 0) return 1; // Show at least 1 page even if no tasks
    return Math.ceil(totalTasks / limit);
}

const Tasks = () => {
    const [tasks, setTasks] = useState([]);
    const [page, setPage] = useState(1);
    const [totalTasks, setTotalTasks] = useState(0);
    const [open, setOpen] = useState(false);
    const [newTask, setNewTask] = useState({ title: '', location: '', description: '', priority: 'Normal' });
    const [snackbar, setSnackbar] = useState<{ open: boolean; message: string; severity: 'success' | 'error' | 'info' | 'warning' }>({
        open: false,
        message: '',
        severity: 'success',
    });
    const [loading, setLoading] = useState(true);

    useEffect(() => {
        fetchTasks();
    }, [page]);

    const fetchTasks = async () => {
        try {
            const response = await client.get('/tasks', {
                params: {
                    page: page,
                    limit
                }
            });
            setTasks(response.data);
            const count = response.headers['x-total-count'];
            setTotalTasks(count ? parseInt(count) : response.data.length);
        } catch (e) {
            console.error(e);
        } finally {
            setLoading(false);
        }
    };

    const handleCloseSnackbar = () => {
        setSnackbar({ ...snackbar, open: false });
    };

    const handleCreate = async () => {
        try {
            await client.post('/tasks/sync', {
                operation: 'CREATE',
                data: {
                    ...newTask,
                    // _id: will be auto generated by mongo if we don't send one? 
                    // No, our strict schema expects _id as string if we defined it that way.
                    // Actually I defined _id: { type: String, required: true } on Backend.
                    // So I must generate one.
                    _id: `WEB-${Date.now()}`,
                    status: 'Pending'
                }
            });
            setOpen(false);
            setNewTask({ title: '', location: '', description: '', priority: 'Normal' });
            fetchTasks();
            setSnackbar({ open: true, message: 'Task created successfully.', severity: 'success' });
        } catch (e) {
            console.error(e);
            setSnackbar({ open: true, message: 'Failed to create task. Please try again.', severity: 'error' });
        }
    };

    if (loading) {
        return (
            <Box sx={{ display: 'flex', justifyContent: 'center', alignItems: 'center', height: '80vh' }}>
                <CircularProgress />
            </Box>
        )
    }

    return (
        <Box>
             <Box sx={{ display: 'flex', justifyContent: 'space-between', mb: 3 }}>
                <Typography variant="h4">Tasks</Typography>
                <Button variant="contained" startIcon={<AddIcon />} onClick={() => setOpen(true)}>Create Task</Button>
            </Box>
            <TableContainer component={Paper}>
                <Table>
                    <TableHead>
                        <TableRow>
                            <TableCell sx={{ fontWeight: 'bold' }}>Title</TableCell>
                            <TableCell sx={{ fontWeight: 'bold' }}>Location</TableCell>
                            <TableCell sx={{ fontWeight: 'bold' }}>Status</TableCell>
                            <TableCell sx={{ fontWeight: 'bold' }}>Priority</TableCell>
                        </TableRow>
                    </TableHead>
                    <TableBody>
                        {tasks?.map((task: any) => (
                            <TableRow key={task._id}>
                                <TableCell>{task.title}</TableCell>
                                <TableCell>{task.location}</TableCell>
                                <TableCell>
                                    <Chip label={task.status} color={task.status === 'Completed' ? 'success' : task.status === 'In Progress' ? 'primary' : 'warning'} />
                                </TableCell>
                                <TableCell>{task.priority}</TableCell>
                            </TableRow>
                        ))}
                    </TableBody>
                </Table>
            </TableContainer>
            <Box sx={{ display: 'flex', justifyContent: 'center', mt: 3 }}>
                <Pagination count={totalPagesCalculator(totalTasks, limit)} shape="rounded" onChange={(_, value) => setPage(value)} />
            </Box>

            <Dialog open={open} onClose={() => setOpen(false)}>
                <DialogTitle>Create New Task</DialogTitle>
                <DialogContent>
                    <TextField
                        autoFocus
                        margin="dense"
                        label="Title"
                        fullWidth
                        value={newTask.title}
                        onChange={(e) => setNewTask({...newTask, title: e.target.value})}
                    />
                     <TextField
                        margin="dense"
                        label="Location"
                        fullWidth
                        value={newTask.location}
                        onChange={(e) => setNewTask({...newTask, location: e.target.value})}
                    />
                     <TextField
                        margin="dense"
                        label="Description"
                        fullWidth
                        multiline
                        rows={3}
                        value={newTask.description}
                        onChange={(e) => setNewTask({...newTask, description: e.target.value})}
                    />
                    <FormControl fullWidth margin="dense">
                        <InputLabel>Priority</InputLabel>
                        <Select
                            value={newTask.priority}
                            label="Priority"
                            onChange={(e) => setNewTask({...newTask, priority: e.target.value})}
                        >
                            <MenuItem value="Normal">Normal</MenuItem>
                            <MenuItem value="High">High</MenuItem>
                            <MenuItem value="Critical">Critical</MenuItem>
                        </Select>
                    </FormControl>
                </DialogContent>
                <DialogActions>
                    <Button onClick={() => setOpen(false)}>Cancel</Button>
                    <Button onClick={handleCreate} variant="contained">Create</Button>
                </DialogActions>
            </Dialog>

            <Snackbar open={snackbar.open} autoHideDuration={6000} onClose={handleCloseSnackbar}>
                <Alert onClose={handleCloseSnackbar} severity={snackbar.severity} sx={{ width: '100%' }}>
                    {snackbar.message}
                </Alert>
            </Snackbar>
        </Box>
    );
};

export default Tasks;
